In [1]:
import pandas as pd

address_df_changelog = pd.read_csv('LLMdata/Address_changelog.csv')
address_df_s = pd.read_csv('LLMdata/Address_s.csv')
address_df_noisy = pd.read_csv('LLMdata/Address_noisy.csv')
contactpoint_df_changelog = pd.read_csv('LLMdata/Contactpoint_changelog.csv')
contactpoint_df_s = pd.read_csv('LLMdata/Contactpoint_s.csv')
contactpoint_df_noisy = pd.read_csv('LLMdata/Contactpoint_noisy.csv')
healthcare_organization_df_changelog = pd.read_csv('LLMdata/HealthcareOrganization_changelog.csv')
healthcare_organization_df_s = pd.read_csv('LLMdata/HealthcareOrganization_s.csv')
healthcare_organization_df_noisy = pd.read_csv('LLMdata/HealthcareOrganization_noisy.csv')
healthcare_organization_df_log = pd.read_csv('LLMdata/HealthcareOrganization_log.csv')
Service_deparment_df_changelog = pd.read_csv('LLMdata/ServiceDepartment_changelog.csv')
Service_deparment_df_s = pd.read_csv('LLMdata/ServiceDepartment_s.csv')
Service_deparment_df_noisy = pd.read_csv('LLMdata/ServiceDepartment_noisy.csv')
Service_deparment_df_log = pd.read_csv('LLMdata/ServiceDepartment_log.csv')

In [2]:
# Rename multiple columns
address_df_changelog = address_df_changelog.rename(columns={
    'identifier': 'original_id', 
    'column': 'field_name',
    'new': 'varied_value',
    'original': 'original_value',
    'variation': 'variation_type'
})

contactpoint_df_changelog = contactpoint_df_changelog.rename(columns={
    'identifier': 'original_id', 
    'column': 'field_name',
    'new': 'varied_value',
    'original': 'original_value',
    'variation': 'variation_type'
})

healthcare_organization_df_changelog = healthcare_organization_df_changelog.rename(columns={
    'identifier': 'original_id', 
    'column': 'field_name',
    'new': 'varied_value',
    'original': 'original_value',
    'variation': 'variation_type'
})

Service_deparment_df_changelog = Service_deparment_df_changelog.rename(columns={
    'identifier': 'original_id', 
    'column': 'field_name',
    'new': 'varied_value',
    'original': 'original_value',
    'variation': 'variation_type'
})

In [3]:
print(address_df_changelog['field_name'].unique())
print(contactpoint_df_changelog['field_name'].unique())
print(healthcare_organization_df_changelog['field_name'].unique())
print(Service_deparment_df_changelog['field_name'].unique())

['postalCode' 'city' 'text' 'country']
['availableLanguage' 'fax' 'phone' 'email']
['healthcareOrganizationName']
['serviceDepartmentName']

In [13]:
address_df_changelog['entity_type'] = 'Address'
contactpoint_df_changelog['entity_type'] = 'ContactPoint'
healthcare_organization_df_changelog['entity_type'] = 'HealthcareOrganization'
Service_deparment_df_changelog['entity_type'] = 'ServiceDepartment'

# HCO ground truth

In [5]:
# Extract unique UUIDs from healthcare_organization_df_log
org_uuids = healthcare_organization_df_log['healthcareOrg_uuid'].unique()
address_uuids = healthcare_organization_df_log['address_uuid'].unique()
contact_uuids = healthcare_organization_df_log['contactPoint_uuid'].unique()
# Filter the changelog dataframes based on these UUIDs
filtered_org_df = healthcare_organization_df_changelog[
    healthcare_organization_df_changelog['original_id'].isin(org_uuids)
]
filtered_address_df = address_df_changelog[
    address_df_changelog['original_id'].isin(address_uuids)
]
filtered_contact_df = contactpoint_df_changelog[
    contactpoint_df_changelog['original_id'].isin(contact_uuids)
] 

# Concatenate the filtered dataframes
combined_entities_df = pd.concat(
    [filtered_org_df, filtered_address_df, filtered_contact_df], 
    ignore_index=False
)
combined_entities_df

,row,original_id,field_name,original_value,varied_value,variation_type,entity_type
0,0,06d2ed7c-e6ac-4d8a-8160-ff927c7550f2,healthcareOrganizationName,Ibarra PLC Zorg,Ibarra PLk Zorg,Organization Name Typo,HealthcareOrganization
1,1,4a863655-0a9d-499c-a269-8c2d614f1ddc,healthcareOrganizationName,"Berg, Long and Middleton Tervisekeskus","Berg, Long and Middleton Terivsekeskus",Organization Name Typo,HealthcareOrganization
2,2,037d9752-48f3-431c-8fb7-c3bb4408c04c,healthcareOrganizationName,"Jordan, Jackson and Kramer Zorg","Jordan, Jackson and Krame rZorg",Organization Name Typo,HealthcareOrganization
3,3,5d393bf9-b2da-41f6-8c16-014a2e4a6e78,healthcareOrganizationName,Perez-Becker Gesundheitszentrum,PG,Organization Name Abbreviation,HealthcareOrganization
4,5,3e332f35-086c-4768-b0fe-3cfc991ab513,healthcareOrganizationName,Novak PLC Tervisekeskus,Noavk PLC Tervisekeskus,Organization Name Typo,HealthcareOrganization
...,...,...,...,...,...,...,...
20,12,29502326-7644-4183-9aab-d22d75ef8aab,phone,(757)762-9481,(757)792-9481,Phone Number Typo,ContactPoint
21,12,29502326-7644-4183-9aab-d22d75ef8aab,fax,(757)680-3429,(757)680-3129,Fax Number Typo,ContactPoint
22,13,fae3fcee-7636-4fd9-8376-ffa876fe579f,fax,456.336.0906x1435,456.336.0906x9435,Fax Number Typo,ContactPoint
23,13,fae3fcee-7636-4fd9-8376-ffa876fe579f,phone,001-293-368-4735,011-293-368-4735,Phone Number Typo,ContactPoint
24,14,eec9fa67-4cc6-42fc-b006-ff85166a1a98,availableLanguage,"['et', 'en']","['Estonian', 'English']",Language Representation Variation,ContactPoint

In [49]:
import re

omission_rows = []

# Iterate through the healthcare_organization_df_log to find omissions
for idx, log_row in healthcare_organization_df_log.iterrows():
    omitted_string = log_row['omitted']
    address_uuid = log_row['address_uuid']
    contact_uuid = log_row['contactPoint_uuid']
   

    # Parse address omissions
    address_match = re.search(r"address: ([\w\s,]+?)(?:, contact:|$)", omitted_string)
    
    if address_match:
        address_fields_str = address_match.group(1).strip()
        if address_fields_str:
            address_fields = [field.strip() for field in address_fields_str.split(',') if field.strip()]
           
            for field_name in address_fields:
                # Fetch original value from address_df_s
                original_value_series = address_df_s[address_df_s['identifier'] == address_uuid][field_name]
                original_value = original_value_series.iloc[0] if not original_value_series.empty else None
                
                
                omission_rows.append({
                    'row': idx,  # Using log_row index as the 'row' identifier
                    'original_id': address_uuid,
                    'field_name': field_name,
                    'original_value': original_value,
                    'varied_value': "",  # Empty as requested
                    'variation_type': 'omission',
                    'entity_type': 'Address'
                })

    # Parse contact point omissions
    contact_match = re.search(r"contact: \[(.*?)\]", omitted_string)
    if contact_match:
        contact_fields_str = contact_match.group(1).strip()
        if contact_fields_str:
            # Handles fields like 'email', 'phone', "'availableLanguage'"
            contact_fields = [field.strip().strip("'").strip('"') for field in contact_fields_str.split(',') if field.strip()]
            for field_name in contact_fields:
                # Fetch original value from contactpoint_df_s
                original_value_series = contactpoint_df_s[contactpoint_df_s['identifier'] == contact_uuid][field_name]
                original_value = original_value_series.iloc[0] if not original_value_series.empty else None
                
                
                omission_rows.append({
                    'row': idx, # Using log_row index as the 'row' identifier
                    'original_id': contact_uuid,
                    'field_name': field_name,
                    'original_value': original_value,
                    'varied_value': "",  # Empty as requested
                    'variation_type': 'omission',
                    'entity_type': 'ContactPoint'
                })

# Create a DataFrame from the omission rows
omissions_df = pd.DataFrame(omission_rows)

# Concatenate the new omission rows with the existing combined_entities_df
if not omissions_df.empty:
    combined_entities_df_om = pd.concat([combined_entities_df, omissions_df], ignore_index=True)

print("Shape of the updated combined_entities_df after adding omissions:", combined_entities_df_om.shape)
print("Few rows from the newly added omission data (if any):")
# Displaying rows that were just added (where variation_type is 'omission')
print(combined_entities_df_om[combined_entities_df_om['variation_type'] == 'omission'].head())

Shape of the updated combined_entities_df after adding omissions: (103, 7)
Few rows from the newly added omission data (if any):
    row                           original_id         field_name  \
70    0  7d859725-c707-4ef9-86c3-744cc88e03b6               text
71    0  ef151673-a1df-4da7-9d44-c93e7799a8e2              email
72    1  6bc9e970-c48a-4374-86dc-1579647640a1               text
73    1  29502326-7644-4183-9aab-d22d75ef8aab  availableLanguage
74    2  6756264d-c864-4f78-beaf-167952b04994            country

           original_value varied_value variation_type   entity_type
70           Jordyring 13                    omission       Address
71  Ibarra@healthcare.org                    omission  ContactPoint
72      Elena Station 124                    omission       Address
73           ['et', 'en']                    omission  ContactPoint
74                     NL                    omission       Address

In [50]:
combined_entities_df_om

,row,original_id,field_name,original_value,varied_value,variation_type,entity_type
0,0,06d2ed7c-e6ac-4d8a-8160-ff927c7550f2,healthcareOrganizationName,Ibarra PLC Zorg,Ibarra PLk Zorg,Organization Name Typo,HealthcareOrganization
1,1,4a863655-0a9d-499c-a269-8c2d614f1ddc,healthcareOrganizationName,"Berg, Long and Middleton Tervisekeskus","Berg, Long and Middleton Terivsekeskus",Organization Name Typo,HealthcareOrganization
2,2,037d9752-48f3-431c-8fb7-c3bb4408c04c,healthcareOrganizationName,"Jordan, Jackson and Kramer Zorg","Jordan, Jackson and Krame rZorg",Organization Name Typo,HealthcareOrganization
3,3,5d393bf9-b2da-41f6-8c16-014a2e4a6e78,healthcareOrganizationName,Perez-Becker Gesundheitszentrum,PG,Organization Name Abbreviation,HealthcareOrganization
4,5,3e332f35-086c-4768-b0fe-3cfc991ab513,healthcareOrganizationName,Novak PLC Tervisekeskus,Noavk PLC Tervisekeskus,Organization Name Typo,HealthcareOrganization
...,...,...,...,...,...,...,...
98,12,7680891b-6bb6-404e-a0db-22d329e316ad,availableLanguage,"['nl', 'en']",,omission,ContactPoint
99,13,bb0378eb-7a62-422e-9d69-d9fc4b1cb8bd,text,Ceylindreef 78,,omission,Address
100,13,122411e6-ba89-42dd-85e6-9ea9db66bfda,fax,+31517-176045,,omission,ContactPoint
101,14,daf66c5f-2577-4ffa-887a-746319c16a0d,postalCode,9573,,omission,Address
102,14,12f175ff-ae3b-46ec-9a27-d85888c132ad,phone,3132991615,,omission,ContactPoint

In [110]:
import numpy as np

# Initialize the 'duplicate_id' column with a default value (e.g., NaN or empty string)
combined_entities_df_om['duplicate_id'] = pd.NA

# Identify rows where 'field_name' is 'healthcareOrganizationName'
mask = combined_entities_df_om['field_name'] == 'healthcareOrganizationName'
# For these rows, create the 'duplicate_id'
# Ensure 'row' is treated as integer for arithmetic and then string for concatenation
combined_entities_df_om.loc[mask, 'duplicate_id'] = 'HCO' + (combined_entities_df_om.loc[mask, 'row'] + 1).astype(str)
# Display the DataFrame with the new column, focusing on relevant rows
print(combined_entities_df_om[combined_entities_df_om['field_name'] == 'healthcareOrganizationName'][['row', 'field_name', 'original_id', 'duplicate_id']].head())
print("\nFull DataFrame head with new column:")
combined_entities_df_om.head()

   row                  field_name                           original_id  \
0    0  healthcareOrganizationName  06d2ed7c-e6ac-4d8a-8160-ff927c7550f2
1    1  healthcareOrganizationName  4a863655-0a9d-499c-a269-8c2d614f1ddc
2    2  healthcareOrganizationName  037d9752-48f3-431c-8fb7-c3bb4408c04c
3    3  healthcareOrganizationName  5d393bf9-b2da-41f6-8c16-014a2e4a6e78
4    5  healthcareOrganizationName  3e332f35-086c-4768-b0fe-3cfc991ab513

  duplicate_id
0         HCO1
1         HCO2
2         HCO3
3         HCO4
4         HCO6

Full DataFrame head with new column:

,row,original_id,field_name,original_value,varied_value,variation_type,entity_type,duplicate_id
0,0,06d2ed7c-e6ac-4d8a-8160-ff927c7550f2,healthcareOrganizationName,Ibarra PLC Zorg,Ibarra PLk Zorg,Organization Name Typo,HealthcareOrganization,HCO1
1,1,4a863655-0a9d-499c-a269-8c2d614f1ddc,healthcareOrganizationName,"Berg, Long and Middleton Tervisekeskus","Berg, Long and Middleton Terivsekeskus",Organization Name Typo,HealthcareOrganization,HCO2
2,2,037d9752-48f3-431c-8fb7-c3bb4408c04c,healthcareOrganizationName,"Jordan, Jackson and Kramer Zorg","Jordan, Jackson and Krame rZorg",Organization Name Typo,HealthcareOrganization,HCO3
3,3,5d393bf9-b2da-41f6-8c16-014a2e4a6e78,healthcareOrganizationName,Perez-Becker Gesundheitszentrum,PG,Organization Name Abbreviation,HealthcareOrganization,HCO4
4,5,3e332f35-086c-4768-b0fe-3cfc991ab513,healthcareOrganizationName,Novak PLC Tervisekeskus,Noavk PLC Tervisekeskus,Organization Name Typo,HealthcareOrganization,HCO6

In [106]:
import rdflib
from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import RDF, RDFS, XSD

In [107]:


# Create an RDF graph
g = Graph()

# Parse the Turtle file
g.parse('src/KGs/healthcareorganizations.ttl', format='turtle')
print(f"Successfully parsed TTL file. Graph contains {len(g)} triples.")
    
# Get a list of all namespaces used in the file
print("\nNamespaces in the file:")
for ns_prefix, namespace in g.namespaces():
    print(f"{ns_prefix}: {namespace}")
    
# Define namespaces that are commonly used
SCHEMA = Namespace("http://schema.org/")
EX = Namespace("http://example.org/")

Successfully parsed TTL file. Graph contains 237 triples.

Namespaces in the file:
owl: http://www.w3.org/2002/07/owl#
rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
rdfs: http://www.w3.org/2000/01/rdf-schema#
xsd: http://www.w3.org/2001/XMLSchema#
xml: http://www.w3.org/XML/1998/namespace
schema: https://schema.org/

In [133]:
# Find all Address and ContactPoint entities in the RDF graph
address_entities = set()
contactpoint_entities = set()

for subj in g.subjects():
    subj_str = str(subj)
    if subj_str.startswith("http://example.org/Address/"):
        address_entities.add(subj)
    elif subj_str.startswith("http://example.org/ContactPoint/"):
        contactpoint_entities.add(subj)


print(contactpoint_entities)
#print("Address entities:", sorted(address_entities))
#print("ContactPoint entities:", sorted(contactpoint_entities))

for sub in address_entities:
    #print(f"Address entity: {sub}")
    for pred in g.predicate_objects(sub):
        #print (f"  Predicate: {pred[0]}")
        if str(pred[0]) == "https://schema.org/addressLocality":
            #print(f"Address entity: {sub}, addressLocality: {pred[1]}")
            if str(pred[1]) in address_df_noisy['city'].values:
                #print(f"Match found in address_df_noisy for addressLocality: {pred[1]}")
                #print(str(sub.split('/')[-1]), str(pred[1]))
                identifier = address_df_noisy.loc[address_df_noisy['city'] == str(pred[1]), 'identifier'].values[0]
                #print(f"Identifier: {identifier}") 
                if identifier in combined_entities_df_om['original_id'].values:
                    # Find the row in combined_entities_df_om with this original_id and update duplicate_id
                    mask = combined_entities_df_om['original_id'] == identifier
                    combined_entities_df_om.loc[mask, 'duplicate_id'] = str(sub.split('/')[-1])
                   
                    #print(f"Address entity: {sub}, addressLocality: {pred[1]}, Identifier: {identifier}")


for sub in contactpoint_entities:
    #print(f"ContactPoint entity: {sub}")
    for pred in g.predicate_objects(sub):
        #print (f"  Predicate: {pred[0]}")
        if str(pred[0]) == "https://schema.org/telephone" or str(pred[0]) == "https://schema.org/email":
            #print(f"ContactPoint entity: {sub}, availableLanguage: {pred[1]}")
            value = str(pred[1])
            if value.endswith('.'):
                value = value[:-1]
            if value in contactpoint_df_noisy['phone'].values:
                matching_rows = contactpoint_df_noisy.loc[contactpoint_df_noisy['phone'] == value, 'identifier']
                if not matching_rows.empty:
                    identifier = matching_rows.values[0]
                    if identifier in combined_entities_df_om['original_id'].values:
                        mask = combined_entities_df_om['original_id'] == identifier
                        combined_entities_df_om.loc[mask, 'duplicate_id'] = str(sub).split('/')[-1]
            
            # Check for email matches with safer approach
            elif value in contactpoint_df_noisy['email'].values:
                matching_rows = contactpoint_df_noisy.loc[contactpoint_df_noisy['email'] == value, 'identifier']
                if not matching_rows.empty:
                    identifier = matching_rows.values[0]
                    if identifier in combined_entities_df_om['original_id'].values:
                        mask = combined_entities_df_om['original_id'] == identifier
                        combined_entities_df_om.loc[mask, 'duplicate_id'] = str(sub).split('/')[-1]


# print("Address entity to addressLocality mapping:")
# for k, v in address_locality_map.items():
#     print(f"{k}: {v}")
# # For each address entity in address_df_noisy, match the addressLocality value with the city value
# # Assuming address_df_noisy has columns: 'identifier', 'addressLocality', 'city'
# if 'addressLocality' in address_df_noisy.columns and 'city' in address_df_noisy.columns:
#     address_df_noisy['addressLocality_matches_city'] = address_df_noisy['addressLocality'] == address_df_noisy['city']
#     print(address_df_noisy[['identifier', 'addressLocality', 'city', 'addressLocality_matches_city']])
# else:
#     print("addressLocality or city column not found in address_df_noisy")

{rdflib.term.URIRef('http://example.org/ContactPoint/CP11'), rdflib.term.URIRef('http://example.org/ContactPoint/CP15'), rdflib.term.URIRef('http://example.org/ContactPoint/CP10'), rdflib.term.URIRef('http://example.org/ContactPoint/CP13'), rdflib.term.URIRef('http://example.org/ContactPoint/CP7'), rdflib.term.URIRef('http://example.org/ContactPoint/CP3'), rdflib.term.URIRef('http://example.org/ContactPoint/CP14'), rdflib.term.URIRef('http://example.org/ContactPoint/CP6'), rdflib.term.URIRef('http://example.org/ContactPoint/CP5'), rdflib.term.URIRef('http://example.org/ContactPoint/CP4'), rdflib.term.URIRef('http://example.org/ContactPoint/CP9'), rdflib.term.URIRef('http://example.org/ContactPoint/CP1'), rdflib.term.URIRef('http://example.org/ContactPoint/CP12'), rdflib.term.URIRef('http://example.org/ContactPoint/CP8'), rdflib.term.URIRef('http://example.org/ContactPoint/CP2')}

In [134]:
combined_entities_df_om

,row,original_id,field_name,original_value,varied_value,variation_type,entity_type,duplicate_id
0,0,06d2ed7c-e6ac-4d8a-8160-ff927c7550f2,healthcareOrganizationName,Ibarra PLC Zorg,Ibarra PLk Zorg,Organization Name Typo,HealthcareOrganization,HCO1
1,1,4a863655-0a9d-499c-a269-8c2d614f1ddc,healthcareOrganizationName,"Berg, Long and Middleton Tervisekeskus","Berg, Long and Middleton Terivsekeskus",Organization Name Typo,HealthcareOrganization,HCO2
2,2,037d9752-48f3-431c-8fb7-c3bb4408c04c,healthcareOrganizationName,"Jordan, Jackson and Kramer Zorg","Jordan, Jackson and Krame rZorg",Organization Name Typo,HealthcareOrganization,HCO3
3,3,5d393bf9-b2da-41f6-8c16-014a2e4a6e78,healthcareOrganizationName,Perez-Becker Gesundheitszentrum,PG,Organization Name Abbreviation,HealthcareOrganization,HCO4
4,5,3e332f35-086c-4768-b0fe-3cfc991ab513,healthcareOrganizationName,Novak PLC Tervisekeskus,Noavk PLC Tervisekeskus,Organization Name Typo,HealthcareOrganization,HCO6
...,...,...,...,...,...,...,...,...
98,12,7680891b-6bb6-404e-a0db-22d329e316ad,availableLanguage,"['nl', 'en']",,omission,ContactPoint,CP13
99,13,bb0378eb-7a62-422e-9d69-d9fc4b1cb8bd,text,Ceylindreef 78,,omission,Address,Ad14
100,13,122411e6-ba89-42dd-85e6-9ea9db66bfda,fax,+31517-176045,,omission,ContactPoint,CP14
101,14,daf66c5f-2577-4ffa-887a-746319c16a0d,postalCode,9573,,omission,Address,Ad15
102,14,12f175ff-ae3b-46ec-9a27-d85888c132ad,phone,3132991615,,omission,ContactPoint,CP15

In [135]:
print(combined_entities_df_om[combined_entities_df_om['duplicate_id'].isna()])

Empty DataFrame
Columns: [row, original_id, field_name, original_value, varied_value, variation_type, entity_type, duplicate_id]
Index: []

In [136]:
combined_entities_df_om.to_csv('ground_truth_HCO.csv', index=False)
print("ground_truth_HCO.csv file created successfully.")

ground_truth_HCO.csv file created successfully.

# SD ground truth

In [15]:
# Extract unique UUIDs from healthcare_organization_df_log
org_uuids = Service_deparment_df_log['healthcareOrg_uuid'].unique()
sd_uuids = Service_deparment_df_log['serviceDept_uuid'].unique()
address_uuids = Service_deparment_df_log['address_uuid'].unique()
contact_uuids = Service_deparment_df_log['contactPoint_uuid'].unique()

# Filter the changelog dataframes based on these UUIDs
filtered_org_df = healthcare_organization_df_changelog[
    healthcare_organization_df_changelog['original_id'].isin(org_uuids)
]
filtered_sd_df = Service_deparment_df_changelog[
    Service_deparment_df_changelog['original_id'].isin(sd_uuids)
]
filtered_address_df = address_df_changelog[
    address_df_changelog['original_id'].isin(address_uuids)
]
filtered_contact_df = contactpoint_df_changelog[
    contactpoint_df_changelog['original_id'].isin(contact_uuids)
]

# Concatenate the filtered dataframes
combined_entities_df = pd.concat(
    [filtered_org_df, filtered_sd_df, filtered_address_df, filtered_contact_df], 
    ignore_index=False
)
combined_entities_df

,row,original_id,field_name,original_value,varied_value,variation_type,entity_type
0,0,06d2ed7c-e6ac-4d8a-8160-ff927c7550f2,healthcareOrganizationName,Ibarra PLC Zorg,Ibarra PLk Zorg,Organization Name Typo,HealthcareOrganization
1,1,4a863655-0a9d-499c-a269-8c2d614f1ddc,healthcareOrganizationName,"Berg, Long and Middleton Tervisekeskus","Berg, Long and Middleton Terivsekeskus",Organization Name Typo,HealthcareOrganization
2,2,037d9752-48f3-431c-8fb7-c3bb4408c04c,healthcareOrganizationName,"Jordan, Jackson and Kramer Zorg","Jordan, Jackson and Krame rZorg",Organization Name Typo,HealthcareOrganization
3,3,5d393bf9-b2da-41f6-8c16-014a2e4a6e78,healthcareOrganizationName,Perez-Becker Gesundheitszentrum,PG,Organization Name Abbreviation,HealthcareOrganization
4,5,3e332f35-086c-4768-b0fe-3cfc991ab513,healthcareOrganizationName,Novak PLC Tervisekeskus,Noavk PLC Tervisekeskus,Organization Name Typo,HealthcareOrganization
...,...,...,...,...,...,...,...
166,98,b81b7f03-fb0a-4705-8e9a-a076faac8f76,phone,(0164) 630310,(1746) 310310,Phone/Fax Number Typo,ContactPoint
167,99,e558abe1-7fc8-42e7-8a2d-e86e6910124a,availableLanguage,['nl'],['Dutch'],Language Representation Variation,ContactPoint
168,100,6706e199-9aaa-4aa8-9bec-11a0d5bccf5e,phone,+31(0)54-7591563,+10(5)59-5631563,Phone/Fax Number Typo,ContactPoint
169,101,68f111c6-ddef-4680-9eb8-39597f119389,email,Burch.Diet@dept.healthcare.org,Burlh.Diet@dept.healthcare.org,Email Typo,ContactPoint
170,102,10d44b3d-8aca-4410-9c10-126197762b3a,availableLanguage,"['nl', 'en']","['Dutch', 'English']",Language Representation Variation,ContactPoint

In [16]:
import re

omission_rows = []

# Iterate through the SD_log to find omissions
for idx, log_row in Service_deparment_df_log.iterrows():
    omitted_string = log_row['omitted']
    address_uuid = log_row['address_uuid']
    contact_uuid = log_row['contactPoint_uuid']
   

    # Parse address omissions
    address_match = re.search(r"address: ([\w\s,]+?)(?:, contact:|$)", omitted_string)
    
    if address_match:
        address_fields_str = address_match.group(1).strip()
        if address_fields_str:
            address_fields = [field.strip() for field in address_fields_str.split(',') if field.strip()]
           
            for field_name in address_fields:
                # Fetch original value from address_df_s
                original_value_series = address_df_s[address_df_s['identifier'] == address_uuid][field_name]
                original_value = original_value_series.iloc[0] if not original_value_series.empty else None
                
                
                omission_rows.append({
                    'row': idx,  # Using log_row index as the 'row' identifier
                    'original_id': address_uuid,
                    'field_name': field_name,
                    'original_value': original_value,
                    'varied_value': "",  # Empty as requested
                    'variation_type': 'omission',
                    'entity_type': 'Address'
                })

    # Parse contact point omissions
    contact_match = re.search(r"contact: \[(.*?)\]", omitted_string)
    if contact_match:
        contact_fields_str = contact_match.group(1).strip()
        if contact_fields_str:
            # Handles fields like 'email', 'phone', "'availableLanguage'"
            contact_fields = [field.strip().strip("'").strip('"') for field in contact_fields_str.split(',') if field.strip()]
            for field_name in contact_fields:
                # Fetch original value from contactpoint_df_s
                original_value_series = contactpoint_df_s[contactpoint_df_s['identifier'] == contact_uuid][field_name]
                original_value = original_value_series.iloc[0] if not original_value_series.empty else None
                
                
                omission_rows.append({
                    'row': idx, # Using log_row index as the 'row' identifier
                    'original_id': contact_uuid,
                    'field_name': field_name,
                    'original_value': original_value,
                    'varied_value': "",  # Empty as requested
                    'variation_type': 'omission',
                    'entity_type': 'ContactPoint'
                })

# Create a DataFrame from the omission rows
omissions_df = pd.DataFrame(omission_rows)

# Concatenate the new omission rows with the existing combined_entities_df
if not omissions_df.empty:
    combined_entities_df_om = pd.concat([combined_entities_df, omissions_df], ignore_index=True)

print("Shape of the updated combined_entities_df after adding omissions:", combined_entities_df_om.shape)
print("Few rows from the newly added omission data (if any):")
# Displaying rows that were just added (where variation_type is 'omission')
print(combined_entities_df_om[combined_entities_df_om['variation_type'] == 'omission'].head())

Shape of the updated combined_entities_df after adding omissions: (705, 7)
Few rows from the newly added omission data (if any):
     row                           original_id         field_name  \
425    0  ea4f44cf-eafd-480b-9ec8-633fb73888a4            country
426    0  42f81126-6c2c-40a7-a4e9-031675f80092  availableLanguage
427    1  60c36cdd-9937-4592-985a-eb983d9f3e80               text
428    1  d41cc2bc-e335-4f8b-91d5-6acf680fe5e2  availableLanguage
429    2  d35f581e-3648-431f-ae9e-8d0384983111         postalCode

                original_value varied_value variation_type   entity_type
425                         AT                    omission       Address
426               ['de', 'en']                    omission  ContactPoint
427  Chris-GrÃ¼nberger-Platz 54                    omission       Address
428               ['de', 'en']                    omission  ContactPoint
429                       9664                    omission       Address

In [19]:
combined_entities_df_om

,row,original_id,field_name,original_value,varied_value,variation_type,entity_type
0,0,06d2ed7c-e6ac-4d8a-8160-ff927c7550f2,healthcareOrganizationName,Ibarra PLC Zorg,Ibarra PLk Zorg,Organization Name Typo,HealthcareOrganization
1,1,4a863655-0a9d-499c-a269-8c2d614f1ddc,healthcareOrganizationName,"Berg, Long and Middleton Tervisekeskus","Berg, Long and Middleton Terivsekeskus",Organization Name Typo,HealthcareOrganization
2,2,037d9752-48f3-431c-8fb7-c3bb4408c04c,healthcareOrganizationName,"Jordan, Jackson and Kramer Zorg","Jordan, Jackson and Krame rZorg",Organization Name Typo,HealthcareOrganization
3,3,5d393bf9-b2da-41f6-8c16-014a2e4a6e78,healthcareOrganizationName,Perez-Becker Gesundheitszentrum,PG,Organization Name Abbreviation,HealthcareOrganization
4,5,3e332f35-086c-4768-b0fe-3cfc991ab513,healthcareOrganizationName,Novak PLC Tervisekeskus,Noavk PLC Tervisekeskus,Organization Name Typo,HealthcareOrganization
...,...,...,...,...,...,...,...
700,111,1ba43eaf-84f4-4346-9301-6d9e87d3b238,country,EE,,omission,Address
701,111,87e87d1f-9af4-402a-8703-a4230fa8aee9,fax,+1-872-295-4400x13981,,omission,ContactPoint
702,111,87e87d1f-9af4-402a-8703-a4230fa8aee9,email,Novak.Gastroenterologic@dept.healthcare.org,,omission,ContactPoint
703,112,572b4813-53e1-4084-8089-a684556ec366,text,Salumets Ramp 103,,omission,Address
704,112,21f04ef1-e253-4910-9e10-c49316197d45,availableLanguage,"['et', 'en']",,omission,ContactPoint

In [26]:
import numpy as np

# Initialize the 'duplicate_id' column with a default value (e.g., NaN or empty string)
combined_entities_df_om['duplicate_id'] = pd.NA

# Identify rows where 'field_name' is 'healthcareOrganizationName'
mask = combined_entities_df_om['field_name'] == 'healthcareOrganizationName'
mask2 = combined_entities_df_om['entity_type'] == 'ServiceDepartment'
# For these rows, create the 'duplicate_id'
# Ensure 'row' is treated as integer for arithmetic and then string for concatenation
combined_entities_df_om.loc[mask, 'duplicate_id'] = 'HCO' + (combined_entities_df_om.loc[mask, 'row'] + 1).astype(str)
combined_entities_df_om.loc[mask2, 'duplicate_id'] = 'SD' + (combined_entities_df_om.loc[mask2, 'row'] + 1).astype(str)
# Display the DataFrame with the new column, focusing on relevant rows
print(combined_entities_df_om[combined_entities_df_om['field_name'] == 'healthcareOrganizationName'][['row', 'field_name', 'original_id', 'duplicate_id']].head())
print("\nFull DataFrame head with new column:")
combined_entities_df_om.head()

   row                  field_name                           original_id  \
0    0  healthcareOrganizationName  06d2ed7c-e6ac-4d8a-8160-ff927c7550f2
1    1  healthcareOrganizationName  4a863655-0a9d-499c-a269-8c2d614f1ddc
2    2  healthcareOrganizationName  037d9752-48f3-431c-8fb7-c3bb4408c04c
3    3  healthcareOrganizationName  5d393bf9-b2da-41f6-8c16-014a2e4a6e78
4    5  healthcareOrganizationName  3e332f35-086c-4768-b0fe-3cfc991ab513

  duplicate_id
0         HCO1
1         HCO2
2         HCO3
3         HCO4
4         HCO6

Full DataFrame head with new column:

,row,original_id,field_name,original_value,varied_value,variation_type,entity_type,duplicate_id
0,0,06d2ed7c-e6ac-4d8a-8160-ff927c7550f2,healthcareOrganizationName,Ibarra PLC Zorg,Ibarra PLk Zorg,Organization Name Typo,HealthcareOrganization,HCO1
1,1,4a863655-0a9d-499c-a269-8c2d614f1ddc,healthcareOrganizationName,"Berg, Long and Middleton Tervisekeskus","Berg, Long and Middleton Terivsekeskus",Organization Name Typo,HealthcareOrganization,HCO2
2,2,037d9752-48f3-431c-8fb7-c3bb4408c04c,healthcareOrganizationName,"Jordan, Jackson and Kramer Zorg","Jordan, Jackson and Krame rZorg",Organization Name Typo,HealthcareOrganization,HCO3
3,3,5d393bf9-b2da-41f6-8c16-014a2e4a6e78,healthcareOrganizationName,Perez-Becker Gesundheitszentrum,PG,Organization Name Abbreviation,HealthcareOrganization,HCO4
4,5,3e332f35-086c-4768-b0fe-3cfc991ab513,healthcareOrganizationName,Novak PLC Tervisekeskus,Noavk PLC Tervisekeskus,Organization Name Typo,HealthcareOrganization,HCO6

In [27]:
combined_entities_df_om[combined_entities_df_om['entity_type'] == 'ServiceDepartment']

,row,original_id,field_name,original_value,varied_value,variation_type,entity_type,duplicate_id
12,0,1f217475-66f0-4769-8909-c1ba18fa5472,serviceDepartmentName,Midwifery,Geburtshilfe,Translation,ServiceDepartment,SD1
13,1,c9d4e1bb-c4d3-4ec2-baf3-d90e586a7302,serviceDepartmentName,Respiratory Therapy,Breathing Support,Alternate Naming,ServiceDepartment,SD2
14,2,aef82d2e-51f8-4e44-924b-ba5b82042c0b,serviceDepartmentName,Obstetric,Pregnancy Care,Alternate Naming,ServiceDepartment,SD3
15,3,09cef0ea-d6ca-4f41-adf1-fe3fefd9373e,serviceDepartmentName,Neurologic,Neurologisch,Translation,ServiceDepartment,SD4
16,4,93c3150d-77c3-404f-9f7a-46b8450000a1,serviceDepartmentName,Surgical,Chirurgisch,Translation,ServiceDepartment,SD5
...,...,...,...,...,...,...,...,...
120,108,c8e7e4e5-d3eb-4a23-b64b-f06e22a23be8,serviceDepartmentName,Otolaryngologic,OtolarÃ¼ngoloogiline,Translation,ServiceDepartment,SD109
121,109,9b4a4276-da41-4bbc-b40b-5ddba649ec91,serviceDepartmentName,Hematologic,Hematoloogiline,Translation,ServiceDepartment,SD110
122,110,b07ce4cb-bc28-4c8c-9e6a-0f46a893e447,serviceDepartmentName,Podiatric,Podiaatriline,Translation,ServiceDepartment,SD111
123,111,473d6d85-56d2-4bf9-9b82-7bb955fc6343,serviceDepartmentName,Gastroenterologic,Gastroenteroloogiline,Translation,ServiceDepartment,SD112
124,112,85bd8d14-3cd3-45dc-8368-557f39795e8c,serviceDepartmentName,Gynecologic,Women's Health,Alternate Naming,ServiceDepartment,SD113

In [29]:
import rdflib
from rdflib import Graph, Namespace, Literal, URIRef
from rdflib.namespace import RDF, RDFS, XSD
# Create an RDF graph
g = Graph()

# Parse the Turtle file
g.parse('src/KGs/servicedepartments.ttl', format='turtle')
print(f"Successfully parsed TTL file. Graph contains {len(g)} triples.")
    
# Get a list of all namespaces used in the file
print("\nNamespaces in the file:")
for ns_prefix, namespace in g.namespaces():
    print(f"{ns_prefix}: {namespace}")
    
# Define namespaces that are commonly used
SCHEMA = Namespace("http://schema.org/")
EX = Namespace("http://example.org/")

Successfully parsed TTL file. Graph contains 1867 triples.

Namespaces in the file:
owl: http://www.w3.org/2002/07/owl#
rdf: http://www.w3.org/1999/02/22-rdf-syntax-ns#
rdfs: http://www.w3.org/2000/01/rdf-schema#
xsd: http://www.w3.org/2001/XMLSchema#
xml: http://www.w3.org/XML/1998/namespace
schema: https://schema.org/

In [33]:
# Find all Address and ContactPoint entities in the RDF graph
address_entities = set()
contactpoint_entities = set()

for subj in g.subjects():
    subj_str = str(subj)
    if subj_str.startswith("http://example.org/Address/"):
        address_entities.add(subj)
    elif subj_str.startswith("http://example.org/ContactPoint/"):
        contactpoint_entities.add(subj)


print(contactpoint_entities)
#print("Address entities:", sorted(address_entities))
#print("ContactPoint entities:", sorted(contactpoint_entities))

for sub in address_entities:
    #print(f"Address entity: {sub}")
    for pred in g.predicate_objects(sub):
        #print (f"  Predicate: {pred[0]}")
        if str(pred[0]) == "https://schema.org/addressLocality":
            #print(f"Address entity: {sub}, addressLocality: {pred[1]}")
            if str(pred[1]) in address_df_noisy['city'].values:
                #print(f"Match found in address_df_noisy for addressLocality: {pred[1]}")
                #print(str(sub.split('/')[-1]), str(pred[1]))
                identifier = address_df_noisy.loc[address_df_noisy['city'] == str(pred[1]), 'identifier'].values[0]
                #print(f"Identifier: {identifier}") 
                if identifier in combined_entities_df_om['original_id'].values:
                    # Find the row in combined_entities_df_om with this original_id and update duplicate_id
                    mask = combined_entities_df_om['original_id'] == identifier
                    combined_entities_df_om.loc[mask, 'duplicate_id'] = str(sub.split('/')[-1])
                   
                    #print(f"Address entity: {sub}, addressLocality: {pred[1]}, Identifier: {identifier}")


for sub in contactpoint_entities:
    #print(f"ContactPoint entity: {sub}")
    for pred in g.predicate_objects(sub):
        #print (f"  Predicate: {pred[0]}")
        if str(pred[0]) == "https://schema.org/telephone" or str(pred[0]) == "https://schema.org/email":
            #print(f"ContactPoint entity: {sub}, availableLanguage: {pred[1]}")
            value = str(pred[1])
            if value.endswith('.'):
                value = value[:-1]
            if value in contactpoint_df_noisy['phone'].values:
                matching_rows = contactpoint_df_noisy.loc[contactpoint_df_noisy['phone'] == value, 'identifier']
                if not matching_rows.empty:
                    identifier = matching_rows.values[0]
                    if identifier in combined_entities_df_om['original_id'].values:
                        mask = combined_entities_df_om['original_id'] == identifier
                        combined_entities_df_om.loc[mask, 'duplicate_id'] = str(sub).split('/')[-1]
            
            # Check for email matches with safer approach
            elif value in contactpoint_df_noisy['email'].values:
                matching_rows = contactpoint_df_noisy.loc[contactpoint_df_noisy['email'] == value, 'identifier']
                if not matching_rows.empty:
                    identifier = matching_rows.values[0]
                    if identifier in combined_entities_df_om['original_id'].values:
                        mask = combined_entities_df_om['original_id'] == identifier
                        combined_entities_df_om.loc[mask, 'duplicate_id'] = str(sub).split('/')[-1]


# print("Address entity to addressLocality mapping:")
# for k, v in address_locality_map.items():
#     print(f"{k}: {v}")
# # For each address entity in address_df_noisy, match the addressLocality value with the city value
# # Assuming address_df_noisy has columns: 'identifier', 'addressLocality', 'city'
# if 'addressLocality' in address_df_noisy.columns and 'city' in address_df_noisy.columns:
#     address_df_noisy['addressLocality_matches_city'] = address_df_noisy['addressLocality'] == address_df_noisy['city']
#     print(address_df_noisy[['identifier', 'addressLocality', 'city', 'addressLocality_matches_city']])
# else:
#     print("addressLocality or city column not found in address_df_noisy")

{rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD73'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD71'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD103'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD99'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD55'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD26'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD112'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD109'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD53'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD20'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD13'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD105'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD74'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD50'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD42'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD16'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD46'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD43'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD39'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD63'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD35'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD14'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD2'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD28'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD91'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD61'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD12'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD86'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD111'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD36'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD69'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD30'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD92'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD4'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD29'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD110'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD11'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD72'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD33'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD7'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD94'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD113'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD77'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD70'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD75'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD19'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD3'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD88'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD96'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD49'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD38'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD59'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD102'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD9'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD6'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD1'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD106'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD31'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD32'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD54'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD79'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD95'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD48'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD85'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD100'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD65'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD90'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD24'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD83'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD47'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD89'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD87'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD98'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD45'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD104'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD34'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD44'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD17'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD8'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD10'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD107'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD67'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD81'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD58'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD78'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD37'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD80'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD97'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD51'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD56'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD40'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD22'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD18'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD41'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD101'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD60'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD5'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD23'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD21'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD84'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD93'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD64'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD62'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD82'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD66'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD25'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD15'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD52'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD27'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD68'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD57'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD108'), rdflib.term.URIRef('http://example.org/ContactPoint/CP_SD76')}

In [34]:
combined_entities_df_om

,row,original_id,field_name,original_value,varied_value,variation_type,entity_type,duplicate_id
0,0,06d2ed7c-e6ac-4d8a-8160-ff927c7550f2,healthcareOrganizationName,Ibarra PLC Zorg,Ibarra PLk Zorg,Organization Name Typo,HealthcareOrganization,HCO1
1,1,4a863655-0a9d-499c-a269-8c2d614f1ddc,healthcareOrganizationName,"Berg, Long and Middleton Tervisekeskus","Berg, Long and Middleton Terivsekeskus",Organization Name Typo,HealthcareOrganization,HCO2
2,2,037d9752-48f3-431c-8fb7-c3bb4408c04c,healthcareOrganizationName,"Jordan, Jackson and Kramer Zorg","Jordan, Jackson and Krame rZorg",Organization Name Typo,HealthcareOrganization,HCO3
3,3,5d393bf9-b2da-41f6-8c16-014a2e4a6e78,healthcareOrganizationName,Perez-Becker Gesundheitszentrum,PG,Organization Name Abbreviation,HealthcareOrganization,HCO4
4,5,3e332f35-086c-4768-b0fe-3cfc991ab513,healthcareOrganizationName,Novak PLC Tervisekeskus,Noavk PLC Tervisekeskus,Organization Name Typo,HealthcareOrganization,HCO6
...,...,...,...,...,...,...,...,...
700,111,1ba43eaf-84f4-4346-9301-6d9e87d3b238,country,EE,,omission,Address,Ad_SD112
701,111,87e87d1f-9af4-402a-8703-a4230fa8aee9,fax,+1-872-295-4400x13981,,omission,ContactPoint,CP_SD112
702,111,87e87d1f-9af4-402a-8703-a4230fa8aee9,email,Novak.Gastroenterologic@dept.healthcare.org,,omission,ContactPoint,CP_SD112
703,112,572b4813-53e1-4084-8089-a684556ec366,text,Salumets Ramp 103,,omission,Address,Ad_SD113
704,112,21f04ef1-e253-4910-9e10-c49316197d45,availableLanguage,"['et', 'en']",,omission,ContactPoint,CP_SD113

In [38]:
print(combined_entities_df_om[combined_entities_df_om['duplicate_id'].isna()])

Empty DataFrame
Columns: [row, original_id, field_name, original_value, varied_value, variation_type, entity_type, duplicate_id]
Index: []

In [37]:
combined_entities_df_om.loc[combined_entities_df_om['original_id'] == 'eb5d11e8-b6d2-4ba9-a517-3d1cf7fc0bd9', 'duplicate_id'] = 'CP_SD13'
combined_entities_df_om.loc[combined_entities_df_om['original_id'] == '0e1cae7a-8122-4b3a-a0b8-024401e32354', 'duplicate_id'] = 'Ad_SD3'
combined_entities_df_om.loc[combined_entities_df_om['original_id'] == 'f929fb27-3e4a-4540-b8b5-c1dece9c85a7', 'duplicate_id'] = 'CP_SD91'

In [39]:
combined_entities_df_om.to_csv('ground_truth_SD.csv', index=False)
print("ground_truth_SD.csv file created successfully.")

ground_truth_SD.csv file created successfully.