# Notebook for sampling the main dataset

In [18]:
import pandas as pd
import os

Address_df = pd.read_csv('Data_source/Sample_15_test/sample_data/Address_s.csv')
ContactPoint_df = pd.read_csv('Data_source/Sample_15_test/sample_data/ContactPoint_s.csv')
HealthcareOrganization_df = pd.read_csv('Data_source/Sample_15_test/sample_data/HealthcareOrganization_s.csv')
HealthcarePersonnel_df = pd.read_csv('Data_source/Sample_15_test/sample_data/HealthcarePersonnel_s.csv')
Person_df = pd.read_csv('Data_source/Sample_15_test/sample_data/Person_s.csv')
ServiceDepartment_df = pd.read_csv('Data_source/Sample_15_test/sample_data/ServiceDepartment_s.csv')

Address = pd.read_csv('Data_source/Baseline/Address.csv')
ContactPoint = pd.read_csv('Data_source/Baseline/ContactPoint.csv')
HealthcareOrganization = pd.read_csv('Data_source/Baseline/HealthcareOrganization.csv')
HealthcarePersonnel = pd.read_csv('Data_source/Baseline/HealthcarePersonnel.csv')
Person = pd.read_csv('Data_source/Baseline/Person.csv')
ServiceDepartment = pd.read_csv('Data_source/Baseline/ServiceDepartment.csv')

In [20]:
# Define dataframe pairs explicitly
dataframes = [
    (Address_df, Address),
    (ContactPoint_df, ContactPoint),
    (HealthcareOrganization_df, HealthcareOrganization),
    (HealthcarePersonnel_df, HealthcarePersonnel),
    (Person_df, Person),
    (ServiceDepartment_df, ServiceDepartment),
]

def remove_subset_by_identifier(subset_df, main_df, key='identifier'):
    subset_ids = subset_df[key].unique()
    return main_df[~main_df[key].isin(subset_ids)].copy()

# Apply the function to each pair
Address_clean, ContactPoint_clean, HealthcareOrganization_clean, HealthcarePersonnel_clean, Person_clean, ServiceDepartment_clean = [
    remove_subset_by_identifier(subset, main) for subset, main in dataframes
]

# Verify the result
print(f"Original Address length: {len(Address)}, Cleaned Address length: {len(Address_clean)}")


# Move all cleaned files to 'Sample_35_train/train_data'
output_dir = os.path.join('Data_source', 'Sample_35_train', 'train_data')
os.makedirs(output_dir, exist_ok=True)

HealthcareOrganization_clean.to_csv(os.path.join(output_dir, 'HealthcareOrganization.csv'), index=False)
HealthcarePersonnel_clean.to_csv(os.path.join(output_dir, 'HealthcarePersonnel.csv'), index=False)
Person_clean.to_csv(os.path.join(output_dir, 'Person.csv'), index=False)
ServiceDepartment_clean.to_csv(os.path.join(output_dir, 'ServiceDepartment.csv'), index=False)
Address_clean.to_csv(os.path.join(output_dir, 'Address.csv'), index=False)
ContactPoint_clean.to_csv(os.path.join(output_dir, 'ContactPoint.csv'), index=False)

print(f"All cleaned files have been moved to '{output_dir}'")

Original Address length: 449, Cleaned Address length: 321
All cleaned files have been moved to 'Data_source\Sample_35_train\train_data'

In [14]:
Address

,identifier,text,city,postalCode,country
0,c8a70639-eb11-47b3-a7a9-c3787c65c1e5,Lukassteeg 84,Oud Zuilen,5579 YN,NL
1,d3290a4c-b5d3-4b16-a619-4cb1d71037d1,Anne Stravenue 82,Andreiside,45067,EE
2,9cdeb3e6-0870-415c-afcd-81b5d24bace4,Kaasik Field 107,Reetbury,64161,EE
3,daf66c5f-2577-4ffa-887a-746319c16a0d,Sulzergasse 127,Kufstein,9573,AT
4,19d5f970-98b3-4c6e-8a14-b90a7795e986,Andrei Parkway 88,Maiechester,20239,EE
...,...,...,...,...,...
444,a5acf1da-2eee-4c46-b558-1ebb398a0e87,Kadri Island 34,Jevgenifort,84956,EE
445,63cb5ee0-a457-4975-9455-4d76109bc754,Rand Point 116,East Tiiuton,54724,EE
446,e9b33269-bd4c-47dc-9c8f-43e5c5b24dc7,Aleksandr Pines 41,South Meelis,74495,EE
447,bd0cda09-0cb3-4bbf-af8c-b8a91754d025,Pukk Mission 3,Triinfurt,51891,EE
448,d9f1b249-8bf4-4ccb-9382-ed7813751d5b,Raag Stream 119,Port Antsmouth,69810,EE