# This file is created to Change the baseline dataset into a dupedataset

In [ ]:
import os
import pandas as pd


noise = 'high'  # Change this to 'low' or 'medium' as needed
# Address_df = pd.read_csv(f'Data_source/Sample_15_test/sample_struct/Address_{noise}.csv')  
# ContactPoint_df = pd.read_csv(f'Data_source/Sample_15_test/sample_struct/ContactPoint_{noise}.csv')
# HealthcareOrganization_df = pd.read_csv(f'Data_source/Sample_15_test/sample_struct/HealthcareOrganization_{noise}.csv')
# HealthcarePersonnel_df = pd.read_csv(f'Data_source/Sample_15_test/sample_struct/HealthcarePersonnel_{noise}.csv')
# Person_df = pd.read_csv(f'Data_source/Sample_15_test/sample_struct/Person_{noise}.csv')
# ServiceDepartment_df = pd.read_csv(f'Data_source/Sample_15_test/sample_struct/ServiceDepartment_{noise}.csv')


Address_df = pd.read_csv(f'Data_source/Sample_35_train/train_struct/Address_{noise}.csv')  
ContactPoint_df = pd.read_csv(f'Data_source/Sample_35_train/train_struct/ContactPoint_{noise}.csv')
HealthcareOrganization_df = pd.read_csv(f'Data_source/Sample_35_train/train_struct/HealthcareOrganization_{noise}.csv')
HealthcarePersonnel_df = pd.read_csv(f'Data_source/Sample_35_train/train_struct/HealthcarePersonnel_{noise}.csv')
Person_df = pd.read_csv(f'Data_source/Sample_35_train/train_struct/Person_{noise}.csv')
ServiceDepartment_df = pd.read_csv(f'Data_source/Sample_35_train/train_struct/ServiceDepartment_{noise}.csv')



entity_dataframes = {
    'Address': Address_df,
    'ContactPoint': ContactPoint_df,
    'HealthcareOrganization': HealthcareOrganization_df,
    'HealthcarePersonnel': HealthcarePersonnel_df,
    'Person': Person_df,
    'ServiceDepartment': ServiceDepartment_df
}

In [21]:
# Rename 'identifier' column to 'anchor' in all entity dataframes

for df in entity_dataframes.values():
    if 'identifier' in df.columns:
        df['anchor'] = df['identifier']

In [22]:
entity_dataframes['Address']

,identifier,text,city,postalCode,country,anchor
0,c8a70639-eb11-47b3-a7a9-c3787c65c1e5,Lukassteeg 84,Oud Zuilen,NaN,NL,c8a70639-eb11-47b3-a7a9-c3787c65c1e5
1,d3290a4c-b5d3-4b16-a619-4cb1d71037d1,Anne Stravenue 82,Andreiside,NaN,EE,d3290a4c-b5d3-4b16-a619-4cb1d71037d1
2,9cdeb3e6-0870-415c-afcd-81b5d24bace4,Kaasik Field 107,Reetbury,NaN,EE,9cdeb3e6-0870-415c-afcd-81b5d24bace4
3,971c702d-5bf4-4c04-ac64-2b4c49b25ded,Pimstraat 126,Lengel,NaN,NL,971c702d-5bf4-4c04-ac64-2b4c49b25ded
4,0cc36d8c-7786-4fe5-9675-ebf74fe30c9a,Cornelius-Mitterer-Ring 83,Sankt Valentin,NaN,AT,0cc36d8c-7786-4fe5-9675-ebf74fe30c9a
...,...,...,...,...,...,...
316,a5acf1da-2eee-4c46-b558-1ebb398a0e87,Kadri Island 34,Jevgenifort,NaN,EE,a5acf1da-2eee-4c46-b558-1ebb398a0e87
317,63cb5ee0-a457-4975-9455-4d76109bc754,Rand Point 116,East Tiiuton,NaN,EE,63cb5ee0-a457-4975-9455-4d76109bc754
318,e9b33269-bd4c-47dc-9c8f-43e5c5b24dc7,Aleksandr Pines 41,South Meelis,NaN,EE,e9b33269-bd4c-47dc-9c8f-43e5c5b24dc7
319,bd0cda09-0cb3-4bbf-af8c-b8a91754d025,Pukk Mission 3,Triinfurt,NaN,EE,bd0cda09-0cb3-4bbf-af8c-b8a91754d025
320,d9f1b249-8bf4-4ccb-9382-ed7813751d5b,Raag Stream 119,Port Antsmouth,NaN,EE,d9f1b249-8bf4-4ccb-9382-ed7813751d5b

In [23]:
from faker import Faker

fake = Faker()

# Create a copy to avoid modifying original data
A_copy = entity_dataframes['Address'].copy()
CP_copy = entity_dataframes['ContactPoint'].copy()
P_copy =  entity_dataframes['Person'].copy()
HO_copy = entity_dataframes['HealthcareOrganization'].copy()
SD_copy = entity_dataframes['ServiceDepartment'].copy()
HP_copy = entity_dataframes['HealthcarePersonnel'].copy()

# Save old values
old_valuesHO = {
    'identifier': HO_copy['identifier'].copy(),
    'address': HO_copy['address'].copy(),
    'contactPoint': HO_copy['contactPoint'].copy()
}

# Generate new UUIDs for each field

HO_copy['identifier'] = HO_copy['identifier'].apply(lambda x: fake.uuid4())
HO_copy['address'] = HO_copy['address'].apply(lambda x: fake.uuid4())
HO_copy['contactPoint'] = HO_copy['contactPoint'].apply(lambda x: fake.uuid4())

# Create copies of dataframes
old_valuesSD = {
    'identifier': SD_copy['identifier'].copy(),
    'address': SD_copy['address'].copy(),
    'contactPoint': SD_copy['contactPoint'].copy()
}

# Generate new UUIDs for each field in ServiceDepartment_df
SD_copy['identifier'] = SD_copy['identifier'].apply(lambda x: fake.uuid4())
SD_copy['address'] = SD_copy['address'].apply(lambda x: fake.uuid4())
SD_copy['contactPoint'] = SD_copy['contactPoint'].apply(lambda x: fake.uuid4())

old_valuesHP = {
    'identifier': HP_copy['identifier'].copy()
}
# Generate new UUIDs for Healthcare Personnel identifiers
HP_copy['identifier'] = HP_copy['identifier'].apply(lambda x: fake.uuid4())

In [24]:
# Create a mapping of old to new UUIDs
HO_uuid_mapping = {
    old_valuesHO['identifier'].iloc[i]: HO_copy['identifier'].iloc[i]
    for i in range(len(HO_copy))
}

# Update references in other dataframes (using the copies)
# Update institution references in Healthcare_Personnel_df copy
HP_copy['institution'] = HP_copy['institution'].map(HO_uuid_mapping).fillna(HP_copy['institution'])

# Update isPartOf references in ServiceDepartment_df copy
SD_copy['isPartOf'] = SD_copy['isPartOf'].map(HO_uuid_mapping).fillna(SD_copy['isPartOf'])

# Update contact point references
ho_contact_mapping = {
    old_valuesHO['contactPoint'].iloc[i]: HO_copy['contactPoint'].iloc[i]
    for i in range(len(HO_copy))
}

# Update identifier in ContactPoint_df copy where it matches old contact points
CP_copy['identifier'] = CP_copy['identifier'].map(ho_contact_mapping).fillna(CP_copy['identifier'])

# Update address references
ho_address_mapping = {
    old_valuesHO['address'].iloc[i]: HO_copy['address'].iloc[i]
    for i in range(len(HO_copy))
}

# Update identifier in Address_df copy where it matches old addresses
A_copy['identifier'] = A_copy['identifier'].map(ho_address_mapping).fillna(A_copy['identifier'])

# Create mapping for ServiceDepartment
sd_uuid_mapping = {
    old_valuesSD['identifier'].iloc[i]: SD_copy['identifier'].iloc[i]
    for i in range(len(SD_copy))
}

# Create address mapping for ServiceDepartment
sd_address_mapping = {
    old_valuesSD['address'].iloc[i]: SD_copy['address'].iloc[i]
    for i in range(len(SD_copy))
}

# Create contact point mapping for ServiceDepartment
sd_contact_mapping = {
    old_valuesSD['contactPoint'].iloc[i]: SD_copy['contactPoint'].iloc[i]
    for i in range(len(SD_copy))
}

# Update references in Address_df copy for ServiceDepartment
A_copy['identifier'] = A_copy['identifier'].map(sd_address_mapping).fillna(A_copy['identifier'])

# Update references in ContactPoint_df copy for ServiceDepartment
CP_copy['identifier'] = CP_copy['identifier'].map(sd_contact_mapping).fillna(CP_copy['identifier'])

# Create mapping for Personnel
hp_uuid_mapping = {
    old_valuesHP['identifier'].iloc[i]: HP_copy['identifier'].iloc[i]
    for i in range(len(HP_copy))
}

# Update references in Person_df copy
P_copy['identifier'] = P_copy['identifier'].map(hp_uuid_mapping).fillna(P_copy['identifier'])

In [25]:
old_valuesHO

{'identifier': 0     71545a13-7a1d-4006-8d72-3104f77383c1
 1     6288e1a5-cc45-4821-98a6-416d1775336d
 2     5f3f5638-3870-4a14-b490-b6081dfc8352
 3     870f084c-7244-4536-a85e-25b4b3969057
 4     ccc14d51-73f6-40d8-a9f4-1cc04653a560
 5     fb5eb866-2640-411e-a9f2-c3c74505f4f6
 6     f2ad985f-ff3e-4ba1-8ac7-28b4a41865bf
 7     c2472fd6-03e9-4a02-8cea-2df00a66dc4e
 8     f164f9d8-4312-4ce2-9c21-51e17e56ac3d
 9     586f1721-0785-48d7-b118-2d235bf80676
 10    4ec985ff-94b2-4b9d-8881-9f421a42b629
 11    788c161e-f3cc-4d8a-8b16-78e45f20f406
 12    48622a67-4a29-4067-9c66-a27b6a325333
 13    862f78e1-25c2-4b6a-b575-bc6eeee84bcb
 14    f46860a2-a604-45af-b4db-1c1eaa66b464
 15    0b5aafef-85a1-482a-8761-585b4168705a
 16    3fee2fc7-2e2d-4fdf-b57b-8a920a12f3b3
 17    1e454241-45c1-40a8-a52b-a0ce627b585f
 18    839137a6-a977-4b71-9e6d-2d7e9f312acb
 19    f1c58f44-7e08-4c1b-8da6-a326451437d6
 20    909b471c-0d1f-4a7f-90fc-e92295be263b
 21    ce8c037e-e51c-4cdb-8247-34dfdd1f8e30
 22    53f3c158-42ce-41c0-8cd9-f2af339c5a75
 23    2ebed37d-05d1-46b6-acee-c38d511fcda9
 24    59cd012a-06b4-4b6f-9f94-e3c818a77594
 25    f172840f-3e19-40ba-ae09-ccfba3dee81f
 26    52526d45-9c68-4df1-8a51-5e8746ba6855
 27    a0c30ce9-57ac-49f2-a887-a3a9e63317c3
 28    8d37aebb-8fc7-47e3-a8b7-4f3dec3826bc
 29    d4e4004b-9bde-499d-9a28-6b7a4d6d99a6
 30    f2684ee1-5ad8-412d-bee1-a2a3024bfe48
 31    1ee1723b-4a96-46a4-a752-41027acf6bcc
 32    062d7f7a-45da-41f3-9a7e-256db6ffe12c
 33    40d2d16f-3db6-42f4-adf2-fc823956fba9
 34    da98da57-166a-4fc4-b513-198c67f8ab57
 Name: identifier, dtype: object,
 'address': 0     c8a70639-eb11-47b3-a7a9-c3787c65c1e5
 1     d3290a4c-b5d3-4b16-a619-4cb1d71037d1
 2     9cdeb3e6-0870-415c-afcd-81b5d24bace4
 3     971c702d-5bf4-4c04-ac64-2b4c49b25ded
 4     0cc36d8c-7786-4fe5-9675-ebf74fe30c9a
 5     4745dd9e-2789-4389-9f32-77fd1d77ce40
 6     15ace7a1-ceca-4ee3-90da-8a9516408169
 7     d3b564b0-8be0-4c3e-9c94-938160c6b3ed
 8     8147a8f4-5f0e-4320-b7f6-0e7f75f2bc20
 9     e38690e7-e27a-48e9-91c3-d1bcc6be6432
 10    24aeba79-e4b8-4987-98ba-0f0e120d7126
 11    c13e66af-3c95-40d3-be2a-ad3e82221345
 12    47b3df41-67c2-4355-8312-1af68b32992a
 13    641659c0-78b6-4daf-9afb-9565068a3c38
 14    6d62e40c-638d-421a-bbc5-9e92ca1209ad
 15    56525ce0-3725-4d0c-b9c4-5c38b440ffe0
 16    4053b188-339d-48f5-9658-b1b33012ae1c
 17    1b770deb-6f51-4a78-bea2-a33a51d11bcd
 18    3dd0c866-0649-4ef5-8fb2-de1ea0b976c2
 19    f4e1680b-05a0-4c72-b22a-4fc63f2de8a8
 20    88239867-c5dd-467b-88f1-100bfa3222c4
 21    fd768f63-5163-4e1d-8df7-a26786fadb0e
 22    067fece7-f1ff-46dc-b45a-a79bd855fb35
 23    8d7f7ba5-72e6-416e-a671-0ad2c1b5468a
 24    4fae667b-b2e7-4e77-8fe1-cedfa5387901
 25    52a33c33-037e-4725-a5a1-bdaea747795e
 26    e9e7e1ba-916b-41ee-afae-feda6b325d48
 27    21d4fb7e-2258-4c89-98cc-f9b4354af1bd
 28    ea31e67a-e168-4205-bc0a-94de4e245cf7
 29    68adc28f-8463-416a-be65-6befe0efc989
 30    8e5f37fa-68f4-4b51-b3fa-861390ed41f4
 31    5e146c30-bd2c-4b8d-b9eb-fa326c1b6811
 32    d24e3104-1dd2-4234-a131-24bd01275a63
 33    51cd2c07-a8f7-4b61-b9d2-b2de92bba701
 34    7176d181-3e2b-4653-a258-edf30ff0952a
 Name: address, dtype: object,
 'contactPoint': 0     23a7711a-8133-4876-b7eb-dcd9e87a1613
 1     b421eaeb-5340-47ca-baf3-897a3e70f16a
 2     09e469e6-ec62-42c8-a648-ee38e07405eb
 3     14aa451c-a69c-4b85-9432-f8db6a174c1c
 4     b9bdee2d-d663-449d-955e-18b1fa83ada4
 5     f24dfdd8-5091-4bdc-8ef0-66d44279b14d
 6     8e751eb7-64d0-4913-991b-8adf0202861c
 7     a36bcb01-67e9-4363-905c-053b25fdacbe
 8     ce1bb02a-cb4d-48d6-adb6-da351734a26c
 9     6d0c62c3-254b-47ae-9d0a-b994f20b575d
 10    1f8941b6-e6a1-440b-b031-f4b9bb6b0095
 11    99e8c828-21da-432c-9c68-d4fd0bd7696f
 12    86ae9d5c-65ff-4adc-81ae-f3f700109824
 13    f305ee95-afb1-40f4-94d4-dad6ddfae808
 14    9626d8c4-344a-4454-b0a6-1c5e707421d4
 15    01d34690-a795-4c54-8a30-f7cd00fdec23
 16    df39ccaa-580c-49fc-bb69-e69041300879
 17    8397d412-7118-4b71-8707-e77b4bf0ae53
 18    584d3c02-0ff9-4318-922a-3a6211091978
 19    6d5b7d50-1417-44f9-b7c1-44fb2b16ad04
 20    58ba0bf3-675e-4c52-9eb9-5739b8acdd81
 21    c0037457-0184-4803-9840-fccb2446ecee
 22    abbf66c7-680a-4e2a-866b-d06fa2b4d215
 23    e55e44b8-08a6-45b4-8321-0210a43c991d
 24    eb1c3ba4-5b9e-42d0-ab0c-9fddb61b03e9
 25    dba45b5e-1498-465b-b9fe-0a1b7efbe877
 26    12b34a24-667f-4eeb-8889-832c37773772
 27    76a933cf-65fd-4f69-93a2-5c9b6e3a52d7
 28    fef06b04-68fc-442a-b6f2-59264e60678b
 29    eb6ec9e0-225f-4457-9662-5aa1056b565f
 30    5c05c1f3-241d-4e27-8bf4-1e101c622f82
 31    c6b7e7cb-be0d-44ed-b306-1611ef96a214
 32    852d2ee5-0061-4d30-9907-3286329cd43a
 33    e93b4418-b170-41ed-9b04-0be38f41d3e4
 34    a54e6c8f-ecb3-477a-acef-5e55840658d1
 Name: contactPoint, dtype: object}

In [26]:
# Dictionary to store all dataframes by entity type

# List of entity types and their corresponding variable names
entity_var_map = {
    'Address': 'A_copy',
    'ContactPoint': 'CP_copy',
    'Person': 'P_copy',
    'HealthcareOrganization': 'HO_copy',
    'ServiceDepartment': 'SD_copy',
    'HealthcarePersonnel': 'HP_copy'
}

# Build the entity_dataframes dictionary dynamically
entity_dataframes_copy = {}
for entity_type, var_name in entity_var_map.items():
    if var_name in locals():
        entity_dataframes_copy[entity_type] = locals()[var_name]
    else:
        print(f"Warning: Variable {var_name} not found for entity type {entity_type}")


# if noise == 'high':
# # Iterate through each row in the golden record
# for _, row in golden_record.iterrows():
#     entity_type = row['entity_type']
    
#     # Check if we have a dataframe for this entity type
#     if entity_type in entity_dataframes_copy:
#         df = entity_dataframes_copy[entity_type]
        
#         # Find the matching row using original_id
#         mask = df['anchor'] == row['original_id']
        
        
#         # If a match is found, update the specified field with the varied value
#         if mask.any():
#             field_name = row['field_name']
#             if field_name in df.columns:
#                 df.loc[mask, field_name] = row['varied_value']  
#             else:
#                 print(f"Warning: Field {field_name} not found in {entity_type} dataframe")
#         else:
#             print(f"Warning: No row with identifier {row['original_id']} found in {entity_type} dataframe")
#     else:
#         print(f"Warning: No dataframe found for entity type {entity_type}")

In [27]:
import pandas as pd

# Function to create omission golden record entries
def create_omission_golden_record(entity_df, entity_type, omitted_fields):
    records = []
    for _, row in entity_df.iterrows():
        for field in omitted_fields:
            if field in row and pd.isna(row[field]):
                records.append({
                    "entity_type": entity_type,
                    "original_id": row["anchor"] if "anchor" in row else row["identifier"],
                    "duplicate_id": row["identifier"],
                    "variation_type": "omission",
                    "field_name": field
                })
    return records

# Define which fields were omitted for each entity type (match your deletion logic)
if noise == 'high':
    omitted_fields_map = {
        'Address': ['text'],
        'Person': ['personName'],
        'HealthcareOrganization': ['healthcareOrganizationName'],
        'ServiceDepartment': ['serviceDepartmentName'],
        'HealthcarePersonnel': ['jobTitle'],
        'ContactPoint': ['contactType'],
    }

if noise == 'low':
    omitted_fields_map = {
        'Address': ['postalCode'],
        'Person': ['birthDate'],
        'HealthcarePersonnel': ['email'],
        'ContactPoint': ['fax'],
    }

# Collect omission records for all entities
omission_golden_records = []
for entity_type, df in entity_dataframes_copy.items():
    omitted_fields = omitted_fields_map.get(entity_type, [])
    omission_golden_records.extend(create_omission_golden_record(df, entity_type, omitted_fields))

# Convert to DataFrame and save
omission_golden_df = pd.DataFrame(omission_golden_records)
omission_golden_df.to_csv(f'train_golden_standard_struct_{noise}.csv', index=False)
omission_golden_df.head()

,entity_type,original_id,duplicate_id,variation_type,field_name
0,Address,c8a70639-eb11-47b3-a7a9-c3787c65c1e5,409a71dc-7808-4048-aa4f-1d1088fc5e79,omission,postalCode
1,Address,d3290a4c-b5d3-4b16-a619-4cb1d71037d1,271727b6-91fc-4a38-b1f9-8f5b0d2b27f2,omission,postalCode
2,Address,9cdeb3e6-0870-415c-afcd-81b5d24bace4,8876d039-8f1b-4334-906f-39a4c465ac57,omission,postalCode
3,Address,971c702d-5bf4-4c04-ac64-2b4c49b25ded,8830c5ae-e4f1-49fc-8b3a-12e0be6e36c2,omission,postalCode
4,Address,0cc36d8c-7786-4fe5-9675-ebf74fe30c9a,069d97d1-b527-4a59-ac94-abddbc48e2a2,omission,postalCode

In [28]:
# Save each entity dataframe copy to a CSV file
for entity_type, df in entity_dataframes_copy.items():
    df.to_csv(f'Data_source/Sample_35_train/train_struct/{entity_type}_{noise}.csv', index=False)

### update duplicate id's